name: Markdown Link Checker

on:
  pull_request:
    branches:
      - master

jobs:
  MarkdownLinkCheck:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: yankeexe/action-link-checker@main
        with:
          file_path: "README.md"
